const nameToPic = {
	braytonlordianto: ["Brayton Lordianto", require("../assets/MemberPictures/brayton.jpeg")],
	nityakuppireddy: ["Nitya Kuppireddy", require("../assets/MemberPictures/nitya.jpg")],
	ianyang: ["Ian Yang", require("../assets/MemberPictures/ian.jpg")],
	divyamadgula: ["Divya Madgula", require("../assets/MemberPictures/divya.png")],
	renatacamargo: ["Renata Camargo", require("../assets/MemberPictures/renata.jpg")],
	shwetasurendar: ["Shweta Surendar", require("../assets/MemberPictures/shweta.jpg")],
	arnavkhinvasara: ["Arnav Khinvasara", require("../assets/MemberPictures/arnav.jpg")],
	kaavyamahendran: ["Kaavya Mahendran", require("../assets/MemberPictures/kaavya.jpg")],
	frankdowner: ["Frank Downer", require("../assets/MemberPictures/frank.jpg")],
	mandypham: ["Mandy Pham", require("../assets/MemberPictures/mandy.jpg")],
	dylandang: ["Dylan Dang", require("../assets/MemberPictures/dylan.jpg")],
	rheaminglani: ["Rhea Minglani", require("../assets/MemberPictures/rhea.jpg")],
	wesleylin: ["Wesley Lin", require("../assets/MemberPictures/wesley.jpg")],
	aaravdesai: ["Aarav Desai", require("../assets/MemberPictures/aarav.jpg")],
	valerieeng: ["Valerie Eng", require("../assets/MemberPictures/valerie.jpg")],
	sophiaclancy: ["Sophia Clancy", require("../assets/MemberPictures/sophia.png")],
}
export { nameToPic }